export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const LIKE_WHINE = 'LIKE_WHINE';
export const UNLIKE_WHINE = 'UNLIKE_WHINE';
export const RE_WHINE = 'RE_WHINE';
export const LOADING_IMAGE = 'LOADING_IMAGE';
export const WHINE_LOADING = 'WHINE_LOADING';
export const USER_FEED = 'USER_FEED';
export const ADD_LIKE_LIST = 'ADD_LIKE_LIST';
export const ADD_UNLIKE_LIST = 'ADD_UNLIKE_LIST';
export const ADD_REWHINE_LIST = 'ADD_REWHINE_LIST';
export const MARK_NOTI_READ = 'MARK_NOTI_READ';
export const DELETE_WHINE = 'DELETE_WHINE';
export const LINK_SENT = 'LINK_SENT';

export const SET_ERRORS = 'SET_ERRORS';
export const SET_PUB_ERRORS = 'SET_PUB_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//DATA REDUCERS

export const LOADING_PUBLIC = 'LOADING_PUBLIC';
export const SET_PUBLIC_DATA = 'SET_PUBLIC_DATA';
export const SET_PUBLIC_WHINES = 'SET_PUBLIC_WHINES';
export const FOLLOW_ACTION = 'FOLLOW_ACTION';
export const UNFOLLOW_ACTION = 'UNFOLLOW_ACTION';
export const FOLLOW_USER_ACTION = 'FOLLOW_USER_ACTION';
export const UNFOLLOW_USER_ACTION = 'UNFOLLOW_USER_ACTION';
export const UNLIKE_WHINE_PUBLIC = 'UNLIKE_WHINE_PUBLIC';
export const LIKE_WHINE_PUBLIC = 'LIKE_WHINE_PUBLIC';
export const RE_WHINE_PUBLIC = 'RE_WHINE_PUBLIC';
export const LOAD_ONE_WHINE = 'LOAD_ONE_WHINE';
export const ONE_WHINE_LOADED = 'ONE_WHINE_LOADED';
export const POSTING_COMMENT = 'POSTING_COMMENT';
export const POSTED_COMMENT = 'POSTED_COMMENT';
export const LOADING_SUGGESTIONS = 'LOADING_SUGGESTIONS';
export const SUGGESTIONS_LOADED = 'SUGGESTIONS_LOADED';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_LOADED = 'SEARCH_LOADED';
export const UPDATING_INFO = 'UPDATING_INFO';
export const UPDATED_INFO = 'UPDATED_INFO';
export const FETCHING_FEED = 'FETCHING_FEED';
export const FETCHED_FEED = 'FETCHED_FEED';
export const NO_MORE_DATA = 'NO_MORE_DATA';
